version: "3.9"
services:
  qcode_ser_qin_desk:
    tty: true
    stdin_open: true
    container_name: qcode_con_qin_desk
    image: pointeldevs/stk_node
    volumes:
      - ${QIN_ROOT}/Work:/root
      - ${QIN_ROOT}/Code:/root/Code
      - ${QIN_ROOT}/Prod:/root/Prod
      - ${QIN_ROOT}/Test:/root/Test
    environment:
      - QIN_ROOT=/root
    networks:
      - qin_net_stk
    working_dir: /root/Code/qin_desk

networks:
  qin_net_stk:
    external: true